services:
    kopia:
        image: kopia/kopia:latest
        hostname: ${HOSTNAME:-kopia}
        container_name: ${CONTAINER_NAME:-kopia}
        user: "1000:1000"
        restart: unless-stopped
        ports:
            - 51515:51515
        # Setup the server that provides the web gui
        command:
            - server
            - start
            - --disable-csrf-token-checks
            - --insecure
            - --address=0.0.0.0:51515
            - --server-username=${USERNAME:-admin}
            - --server-password=${SECRET_PASSWORD}
        environment:
          - TZ=${TZ:-Europe/Madrid}
          # Set repository password
          - KOPIA_PASSWORD=${KOPIA_PASSWORD}
          - USER=${USERNAME:-admin}
          # R2 Cloudflare repository (optional)
          - KOPIA_R2_BUCKET=${KOPIA_R2_BUCKET}
          - KOPIA_R2_ENDPOINT=${KOPIA_R2_ENDPOINT}
          - KOPIA_R2_ACCESS_KEY=${KOPIA_R2_ACCESS_KEY}
          - KOPIA_R2_SECRET_KEY=${KOPIA_R2_SECRET_KEY}
          - KOPIA_R2_PREFIX=${KOPIA_R2_PREFIX}
        volumes:
            # Mount local folders needed by kopia
            - ./config:/app/config
            - ./cache:/app/cache
            - ./logs:/app/logs
            - ./restore:/restore
            - ./tmp:/tmp:shared
            # Mount local folders to snapshot
            - ${KOPIA_DATA_DIR}:/data:ro
            # Mount repository location
            - ${KOPIA_REPOSITORY_DIR}:/repository

# Anadir estas lineas para red externa de proxy inverso
networks:
  default:
    external: true
    name: proxy
